### ISSUE TITLE
Support Namespaces

### ISSUE THREAD

**Issue by v1ar31** [mk1990/Properties2JsonPlugin#1]
We can replace [npm/properties-parser](https://github.com/mkurcius/Properties2JsonPlugin/blob/master/index.js#L2) to [npm/properties](https://github.com/gagle/node-properties)?

![2017-12-12 11_47_54-clipboard](https://user-images.githubusercontent.com/5954269/33875137-53758ac0-df32-11e7-9d71-9cdcd7b3c3da.png)

**Comment by mkurcius** [comment]
Hi, thank you for contribution :)
I will try to look at it as soon as possible

**Comment by mkurcius** [comment]
@v1ar31 merged and published as 1.0.5
Thanks again for contribution 

Happy holidays!

**Comment by v1ar31** [comment]
@mkurcius Thanks for publishing! Happy holidays :)
