### ISSUE TITLE
prefix "module.exports =" to json

### ISSUE THREAD

**Issue by dewezlopez** [mk1990/Properties2JsonPlugin#4]
Needed to have ability to add `module.exports =` to the outputted file for a project.

#3

**Comment by mkurcius** [comment]
Can you tell me more about why you need this feature?
If your motivation is to simply require this file somewhere else, you can just do
```js
const json = require('./somefile.json')
```

**Comment by dewezlopez** [comment]
Sorry about the delay. It's another package which is pulling the json data to render the velocity templates. 

https://github.com/yuanwen0327/velocity-render-loader

Please let me know if I can do anything differently. Thanks in advance.

**Comment by mkurcius** [comment]
I guess you want to generate this `a.mock.js`, right?
To achieve that you can manually create this file with content:

```js
module.exports = require('./somefile.json')
```

:)

**Comment by dewezlopez** [comment]
Thanks so much for your help :)

**Comment by mkurcius** [comment]
Glad could help :)
